apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image: quay.io/keycloak/keycloak:14.0.0
        ports:
        - containerPort: 8080
        env:
        - name: KC_DB
          value: postgres 
        - name: KC_DB_URL_HOST
          value: postgres_keycloak_demo
        - name: KC_DB_URL_DATABASE
          value: keycloak
        - name: KC_DB_USERNAME
          value: keycloak
        - name: KC_DB_PASSWORD
          value: password
        - name: KEYCLOAK_ADMIN
          value: admin
        - name: KEYCLOAK_ADMIN_PASSWORD
          value: admin
        volumeMounts:
        - name: keycloak-data
          mountPath: /opt/jboss/keycloak/data
      volumes:
      - name: keycloak-data
        emptyDir: {}