apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-keycloak-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-keycloak-demo
  template:
    metadata:
      labels:
        app: postgres-keycloak-demo
    spec:
      containers:
        - name: postgres
          image: postgres:14.2
          command: ["postgres", "-c", "max_connections=208"]
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: keycloak
            - name: POSTGRES_USER
              value: keycloak
            - name: POSTGRES_PASSWORD
              value: password
          readinessProbe:
            exec:
              command: ["pg_isready", "-q", "-d", "keycloak", "-U", "keycloak"]
            initialDelaySeconds: 5
            periodSeconds: 10
