name: monitoring CI CD

on:
  push:
    branches:
      - main

jobs:
  sonarQubeScan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: SonarQube Scan
        uses: sonarsource/sonar-scanner-action@v1
        with:
          args: >
            -Dsonar.projectKey=nidhal19615_monitoring-application_e29b7668-e594-4920-af70-4d7bcf98e825
            -Dsonar.sources=.
            -Dsonar.host.url=http://20.19.152.44:9000
            -Dsonar.login=${{ secrets.SONAR_KEY }}
  # publish_image:
  #   runs-on: ubuntu-latest

  #  steps:
  #   - name: Checkout
  #     uses: actions/checkout@v4

#      - name: build
#       run: |
#        docker build --no-cache -t nidhal2/pfe:3.0 .

#   - name: publish
#    run: |
#     docker login -u nidhal2 -p ${{secrets.DOCKER_HUB_TOKEN}}
#    docker push nidhal2/pfe:3.0

#    - name: "Login via Azure CLI"
#     id: azure_login
#     uses: azure/login@v1

#        with:
#          creds: ${{ secrets.AZURE_CREDENTIALS }}
#      - name: Check Azure Login
#        run: |
#          az account show#

#    - name: Get AKS Credentials
#      if: steps.azure_login.outcome == 'success' # Onlyy get credentials if Azure login was successfu
#      run: az aks get-credentials --resource-group ressource-pfe --name cluster-pfe --overwrite-existing

#    - name: K8S Deploy
#     if: steps.azure_login.outcome == 'success' # Only FBHdeployhh if Azkkure login was successfuljj
#    uses: azure/k8s-deploy@v1
#    with:
#      namespace: default
#     manifests: |
#      manifests/react.yml
#   postgres.yml
#  keycloak.yml
