name: monitoring CI CD

on:
  push:
    branches:
      - main

jobs:
  publish_image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: build
        run: |
          docker build -t pfe .

      - name: publish
        run: |
          docker login -u nidhal2 -p ${{secrets.DOCKER_HUB_TOKEN}}
          docker push nidhal2/pfe
