name: monitoring CI CD

on:
  push:
    branches:
      - main

jobs:
  publish_image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: build
        run: |
          docker build . -t nidhal2/pfe:latest

      - name: publish
        run: |
          docker login -u nidhal2 -p ${{secrets.DOCKER_HUB_TOKEN}}
          docker push nidhal2/pfe

      - name: "Login via Azure CLI"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Apply Kubernetes configuration
        run: |
          kubectl apply -f react.yml --validate=false
